# Generated by Django 2.2.3 on 2019-07-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choce_text',
            new_name='choice_text',
        ),
    ]
